//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Web.DataServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public bool IsAnswer { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
