//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz.Web.DataServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizResult
    {
        public int SNo { get; set; }
        public Nullable<int> AttemptId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> SelectedAnswer { get; set; }
    
        public virtual Option Option { get; set; }
        public virtual Question Question { get; set; }
        public virtual QuizAttemptDetail QuizAttemptDetail { get; set; }
    }
}
